Beryllium Back-End/Models/Work.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Beryllium_Back_End.Models
{
    public class Work
    {
        public int Id { get; set; }
        public string WorkName { get; set; }
        public string WorkDescription { get; set; }
        public string WorkIcon { get; set; }
    }
}

Beryllium Back-End/Areas/BeryAdmin/Controllers/WorkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Beryllium_Back_End.DAL;
using Beryllium_Back_End.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Beryllium_Back_End.Areas.BeryAdmin.Controllers
{
    [Area("BeryAdmin")]
    public class WorkController : Controller
    {
        private readonly AppDbContext _context;

        public WorkController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<Work> works = await _context.Works.ToListAsync();
            return View(works);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]

        public async Task<IActionResult> Create(Work work)
        {
            if (!ModelState.IsValid) return NotFound();

            _context.Works.Add(work);
            await _context.SaveChangesAsync();

            return RedirectToAction();
        }

        public async Task<IActionResult> Edit(int id)
        {
            Work work = await _context.Works.FirstOrDefaultAsync(w => w.Id == id);

            if (work == null) return NotFound();

            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]

        public async Task<IActionResult> Edit(int id,Work work)
        {
            if (!ModelState.IsValid) return NotFound();
            Work existedWork = await _context.Works.FirstOrDefaultAsync(w => w.Id == id);

            if (existedWork == null) return View();

            existedWork.WorkName = work.WorkName;
            existedWork.WorkDescription = work.WorkDescription;
            existedWork.WorkIcon = work.WorkIcon;

            if(id != work.Id)
            {
                return BadRequest();
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            Work work = await _context.Works.FirstOrDefaultAsync(w => w.Id == id);
            if (work == null) return NotFound();

            return View(work);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [ActionName("Delete")]

        public async Task<IActionResult> DeleteWork(int id)
        {
            if (!ModelState.IsValid) return View();
            Work work = await _context.Works.FirstOrDefaultAsync(w => w.Id == id);

            if (work == null) return NotFound();

            _context.Works.Remove(work);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Detail(int id)
        {
            if (!ModelState.IsValid) return NotFound();

            Work work = await _context.Works.FirstOrDefaultAsync(w => w.Id == id);

            return View(work);
        }
    }
}

Beryllium Back-End/Areas/BeryAdmin/Views/Work/Create.cshtml
@model Work
@{
    ViewData["Title"] = "Create";
}
<form method="post" enctype="multipart/form-data">
    <div>
        <label>Location:</label>
        <input asp-for="WorkName" class="form-control" />
        <span asp-validation-for="WorkName"></span>
    </div>
    <div>
        <label>Town:</label>
        <input asp-for="WorkDescription" class="form-control" />
        <span asp-validation-for="WorkDescription"></span>
    </div>
    <div>
        <label>Image:</label>
        <input asp-for="WorkIcon" class="form-control" />
        <span asp-validation-for="WorkIcon" class="text-danger"></span>
    </div>
    <div class="mt-3">
        <button type="submit" class="btn btn-danger">Create</button>
    </div>
</form>

Beryllium Back-End/Areas/BeryAdmin/Views/Work/Delete.cshtml
@model Work
@{
    ViewData["Title"] = "Delete";
}

<div>
    <div>
        <p>Work Name:</p>
        <h4>@Model.WorkName</h4>
    </div>
    <div>
        <p>Work Description:</p>
        <h4>@Model.WorkDescription</h4>
    </div>
    <div>
        <p>Work Icon:</p>
        <h4>@Model.WorkIcon</h4>
    </div>
</div>

<form method="post">
    <div class="mt-3">
        <button type="submit" class="btn btn-danger">Delete</button>
    </div>
</form>

Beryllium Back-End/Areas/BeryAdmin/Views/Work/Detail.cshtml
@model Work
@{
    ViewData["Title"] = "Detail";
}

<div>
    <div>
        <p>Name:</p>
        <h4>@Model.WorkName</h4>
    </div>
    <div>
        <p>Description:</p>
        <h4>@Model.WorkDescription</h4>
    </div>
    <div>
        <p>Icon:</p>
        <h4>@Model.WorkIcon</h4>
    </div>
</div>

Beryllium Back-End/Areas/BeryAdmin/Views/Work/Edit.cshtml
@model Work
@{
    ViewData["Title"] = "Edit";
}

<form method="post" enctype="multipart/form-data">
    <div>
        <label>Work Name:</label>
        <input asp-for="WorkName" class="form-control" />
        <span asp-validation-for="WorkName"></span>
    </div>
    <div>
        <label>Work Description:</label>
        <input asp-for="WorkDescription" class="form-control" />
        <span asp-validation-for="WorkDescription"></span>
    </div>
    <div>
        <label>Icon:</label>
        <input asp-for="WorkIcon" class="form-control" />
        <span asp-validation-for="WorkIcon" class="text-danger"></span>
    </div>
    <div class="mt-3">
        <button type="submit" class="btn btn-danger">Edit</button>
    </div>
</form>

Beryllium Back-End/Areas/BeryAdmin/Views/Work/Index.cshtml
@model List<Work>
@{
    ViewData["Title"] = "Index";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Inverse table</h4>
            <a asp-controller="Work" asp-action="Create" class="btn btn-danger">Create</a>
            <div class="table-responsive pt-3">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th>
                                Id
                            </th>
                            <th>
                                Work Name
                            </th>
                            <th>
                                Work Description
                            </th>
                            <th>
                                Work Icon
                            </th>
                            <th>
                                Setting
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Work work in Model)
                        {
                        <tr>
                            <td>
                                @work.Id
                            </td>
                            <td>
                                @work.WorkName
                            </td>
                            <td>
                                @work.WorkDescription
                            </td>
                            <td>
                                @work.WorkIcon
                            </td>
                            <td>
                                <div class="d-flex">
                                    <div>
                                        <a class="btn btn-primary" asp-controller="Work" asp-action="Detail" asp-route-id="@work.Id">
                                            <i class="mdi mdi-details"></i>
                                        </a>
                                    </div>
                                    <div>
                                        <a class="btn btn-success" asp-controller="Work" asp-action="Edit" asp-route-id="@work.Id">
                                            <i class="mdi mdi-tooltip-edit"></i>
                                        </a>
                                    </div>
                                    <div>
                                        <a class="btn btn-danger" asp-controller="Work" asp-action="Delete" asp-route-id="@work.Id">
                                            <i class="mdi mdi-delete-forever"></i>
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>